### ISSUE TITLE
Error in latrendBatch

### ISSUE THREAD

**Issue by hichew22** [philips-software/latrend#135]
Hello,

I have an issue with using latrendBatch with the DTW clustering method. When I try to fit a list of lcMethod objects with the latrendBatch function, I get an error that says: Error in { : task 1 failed - "At least two clusters must be defined." This occurs even when I set nClusters = 1:2.

Here is my code below:

data(latrendData)
methods <- lcMethods(lcMethodDtwclust("Y", id = "Id", time = "Time"), nClusters = 1:3)
models <- latrendBatch(methods, data = latrendData)

I would appreciate your help resolving this issue!

**Comment by niekdt** [comment]
hi, the dtwclust package does not support fitting 1 cluster, hence the error. Most of the other methods (if not all) do support it.

Implementing a special case for the 1-cluster solution might not be straightforward, as the dtwclust package has its own notion of a cluster center (centroids). I need to check if there is a way to compute this for a single-cluster solution using the available package functionality, to ensure consistency.

**Comment by hichew22** [comment]
Got it! It works now if I change nClusters to start at 2. Thank you very much!
