### ISSUE TITLE
error in latent profile analysis function

### ISSUE THREAD

**Issue by janstochl** [philips-software/latrend#138]
Hi, I cannot make the latent profile function work, I get the following error:

> llpa <- lcMethodMclustLLPA("hae3",id = "subjid", time = "tpn", nClusters = 2)
> model <- latrend(llpa, hae_3)
         ------------------------------------------------------------------
         - Longitudinal clustering using: longitudinal latent profile analysis
         ------------------------------------------------------------------
         Method arguments:
          time:           "tpn"
          id:             "subjid"
          nClusters:      2
          modelNames:     NULL
          prior:          NULL
          control:        emControl()
          initialization: NULL
          warn:           mclust.options("warn")
          x:              NULL
          response:       "hae3"
         ------------------------------------------------------------------
         Checking and transforming the training data format.
         Preparing the training data for fitting...
         Fitting the method...
fitting ...
  |========                                                                                                              |   7%Error in meEII(data = data, z = z, prior = prior, control = control, warn = warn) : 
  NA/NaN/Inf in foreign function call (arg 2)

FYI my data ndo not include any Inf, NA or NaN values. It looks like it is related to specification of argument "z" in mclust function  meEII, which according to mclust package is 
"A matrix whose [i,k]th entry is the conditional probability of the ith observation belonging to the kth component of the mixture."

Can you kindly check the issue please?

Thanks,
Jan

**Comment by niekdt** [comment]
Hi, the error thrown by the `mclust::Mclust` function is usually caused by convergence problems. 

Before diving deeper, you may first want to try to:

- Check if all subjects have an observation for each moment in time. Run `tsmatrix(hae_3, id = 'subjid', time = 'tpn', response = 'hae3', fill = FALSE)`, which should throw an error if this requirement is not satisfied.
- Rescale your 'hae3' variable, e.g., using `scale()`. This is typically the cause of convergence problem.
- Simplify the model being estimated: not applicable to your case, but I just wanted to list it for completeness.
- Run the model on fewer time points per subject
- Run the model on fewer subjects
- Weaken the convergence conditions by specifying `control = emControl(...)` in the lcMethod specification, see `mclust::emControl` for details.

Hope this helps

**Comment by janstochl** [comment]
Dear Niek,
many thanks for your helpful response. The issue was indeed that some individuals did not have all timepoints in the datasets. I did not know this was a requirement for mclust. This is quite restrictive as it is often the case that some timepoints are missing, You also cannot add them (and fill with missing values) since missing data are not allowed in mclust either. Strange.

Anyway, I wanted to thank you very much for your kind guidance and also for fantastic latrend package.

All the best,
Jan

Dne 14.09.2023 15:46:06, Niek Den Teuling ***@***.***> napsal:

Hi, the error thrown by the mclust::Mclust function is usually caused by convergence problems.

Before diving deeper, you may first want to try to:

  *   Check if all subjects have an observation for each moment in time. Run tsmatrix(hae_3, id = 'subjid', time = 'tpn', response = 'hae3', fill = FALSE), which should throw an error if this requirement is not satisfied.
  *   Rescale your 'hae3' variable, e.g., using scale(). This is typically the cause of convergence problem.
  *   Simplify the model being estimated: not applicable to your case, but I just wanted to list it for completeness.
  *   Run the model on fewer time points per subject
  *   Run the model on fewer subjects
  *   Weaken the convergence conditions by specifying control = emControl(...) in the lcMethod specification, see mclust::emControl for details.

Hope this helps

**Comment by niekdt** [comment]
Dear Jan,

It is restrictive indeed, but there are alternatives. If the missing data mechanism is non-informative, consider imputing the values, or use a parametric method. The *kml* package has some built-in options to impute data, which you can use through `lcMethodKML`. For a parametric approach that can yield results similar to LLPA, GBTM is a good option (see `lcMethodLcmmGBTM`.

If data is MNAR then you're in rough terrain as standard methods will not be applicable. Pattern mixture modeling will be of help here.

Best regards,
Niek

**Comment by janstochl** [comment]
That is super helpful, thank you Niek.

Jan

Dne 18.09.2023 9:17:11, Niek Den Teuling ***@***.***> napsal:

Dear Jan,

It is restrictive indeed, but there are alternatives. If the missing data mechanism is non-informative, consider imputing the values, or use a parametric method. The kml package has some built-in options to impute data, which you can use through lcMethodKML. For a parametric approach that can yield results similar to LLPA, GBTM is a good option (see lcMethodLcmmGBTM.

If data is MNAR then you're in rough terrain as standard methods will not be applicable. Pattern mixture modeling will be of help here.

Best regards,
Niek
