### ISSUE TITLE
Font size in plot()

### ISSUE THREAD

**Issue by hichew22** [philips-software/latrend#140]
Hello,

I was wondering how to increase the font size of the cluster labels in the plot() function. For example, I am plotting a KML model with 4 clusters. I understand that size increases the thickness of the line (geom_line). How do I increase the labels of the clusters? They appear to be facets.

p_kml <- plot(kml_model_4,
              size = 2)
p_kml

Thank you!

**Comment by hichew22** [comment]
Sorry, I figured it out - using strip.text.x within the theme() function solves this!

**Comment by niekdt** [comment]
Thanks for posting the answer!
