### ISSUE TITLE
Ordering clusters in plotClusterTrajectories()

### ISSUE THREAD

**Issue by hichew22** [philips-software/latrend#144]
Hello Niek,

I am using the dtw method in latrend to plot some clusters like so:
`plotClusterTrajectories(dtw_model_2)`
<img width="405" alt="image" src="https://github.com/philips-software/latrend/assets/137368713/b6397fbd-d70f-4249-86f5-f2ad6e3f1ac2">

or `plot(dtw_model_2)`
<img width="404" alt="image" src="https://github.com/philips-software/latrend/assets/137368713/1d069502-127a-4f8b-8960-41d4ebb8d0f9">

Is there a way within plotClusterTrajectories() where I can specify that the cluster with more values is always listed as cluster "A" (highest frequency to lowest frequency)?

Or would I need to reorder them manually, something like:
```
# Create dataframe with cluster assignments and UPNs
cluster_dtw <- trajectoryAssignments(dtw_model_2)
upn <- ids(dtw_model_2)
df_cluster_dtw <- cbind(cluster_dtw, upn) %>%
  as.data.frame()

# Recode clusters from largest (1) to smallest (2)
cluster_freq <- table(df_cluster_dtw$cluster_dtw)
ordered_clusters <- names(sort(cluster_freq, decreasing = TRUE))
df_cluster_dtw$cluster_dtw <-
  factor(
    df_cluster_dtw$cluster_dtw,
    levels = ordered_clusters,
    labels = seq_along(ordered_clusters)
  ) 

# Create column with cluster labels and percentages
cluster_percentages <- prop.table(table(df_cluster_dtw$cluster_dtw))
cluster_labels = sprintf("%s (%d%%)", names(cluster_percentages), round(cluster_percentages * 100))

df_cluster_dtw <- df_cluster_dtw %>%
  mutate(cluster_label = factor(
    cluster_dtw,
    levels = names(cluster_percentages),
    labels = cluster_labels
  ))

# Add cluster assignments to df_long
df_long <- df_long %>%
  left_join(df_cluster_dtw, by = "id")

# Plot cluster trajectories
latrend::plotClusterTrajectories(
  df_long,
  response = "value",
  cluster = "cluster_label",
  trajectories = TRUE,
  facet = TRUE,
  size = 2
)
```
?

Thank you!

**Comment by niekdt** [comment]
Hi @hichew22, thanks for the suggestion. It's a useful feature to have, especially when comparing similar cluster solutions.

I'll start with adding an argument to plotClusterTrajectories for specifying which clusters to plot, and the ordering.
Ultimately, having a wrapper `lcModel` class for which you can specify the ordering logic would be best. But that'll take some more effort.

**Comment by niekdt** [comment]
`plotClusterTrajectories` now has a `clusterOrder` argument allowing you to specify which clusters to plot, and the order thereof. Either by name or index

**Comment by hichew22** [comment]
Awesome, thanks, Niek! Do you have an example, and does this also allow ordering clusters from most to least frequent?

**Comment by niekdt** [comment]
You're welcome! 

```R
data(latrendData)
method <- lcMethodLMKM(Y ~ Time, id = "Id", time = "Time")
model <- latrend(method, latrendData, nClusters = 3)

# change cluster order
plotClusterTrajectories(model, clusterOrder = c('B', 'C', 'A'))

# show only specific clusters
plotClusterTrajectories(model, clusterOrder = c('B', 'C'))
```

It's intended as a quick way to set a custom order, but to dynamically order by cluster size, you can use:
```R
plotClusterTrajectories(model, clusterOrder = order(-clusterSizes(model)))
```

In the future I intend to add some `lcModel` wrapper classes that would automatically relabel clusters based on some criterion, so the ordening would then be handled during the latrend fitting procedure.

**Comment by hichew22** [comment]
I tried doing that for a 4-cluster DTW model as such:
plotClusterTrajectories(dtw_model_4, clusterOrder = order(-clusterSizes(dtw_model_4)))

However, the clusters do not appear ordered. I did make sure to download the most recent installation of latrend. Could you help me with this?
<img width="537" alt="image" src="https://github.com/philips-software/latrend/assets/137368713/759a7c84-2610-44f5-8fb6-8171e3c73457">

**Comment by niekdt** [comment]
Did you install the latest commit (not release)?

`remotes::install_github('philips-software/latrend')`

**Comment by hichew22** [comment]
Yes, I just did but seems like the function does not work.

─  preparing ‘latrend’: (555ms)
✔  checking DESCRIPTION meta-information ...
─  installing the package to process help pages (811ms)
   Loading required namespace: latrend
─  saving partial Rd database (3.1s)
─  checking for LF line-endings in source and make files and shell scripts (335ms)
─  checking for empty or unneeded directories
─  building ‘latrend_1.5.1.tar.gz’

**Comment by niekdt** [comment]
I can't spot any issues in the source code. Could you let me know what the output is of:

```R
latrend:::make.orderedClusterNames(clusterNames(dtw_model_4), order(-clusterSizes(dtw_model_4)))
```

**Comment by hichew22** [comment]
I just tried re-running it and it works now! Perhaps I had to restart my R session. Thank you so much!
