### ISSUE TITLE
`clusterCrit` again on CRAN

### ISSUE THREAD

**Issue by iago-pssjd** [philips-software/latrend#145]
Hi,

Regarding

https://github.com/philips-software/latrend/blob/821d65bc611e84c0f445c19078f1dc6d33ac0fca/DESCRIPTION#L10
and 
https://github.com/philips-software/latrend/blob/821d65bc611e84c0f445c19078f1dc6d33ac0fca/DESCRIPTION#L84

and any other issues (#131, ...) you may have experienced.

Just to comment `clusterCrit` is again on CRAN with version 1.3.0 (https://cran.r-project.org/web/packages/clusterCrit/index.html).

Thanks!

**Comment by niekdt** [comment]
Thanks for notifying, and for your effort to get the package back on CRAN.

I will update the description accordingly.
