### ISSUE TITLE
Obtaining trajectory values

### ISSUE THREAD

**Issue by hichew22** [philips-software/latrend#149]
Hi Niek,

When trajectories are obtained, for example like in KML:
`kml_model_4 <- subset(kml_models, nClusters == 4, drop = TRUE)`

Is there a way to extract the trajectory value (mean) at each timepoint? For instance, I would want to know what is the lowest value (nadir) of each trajectory here:

<img width="504" alt="image" src="https://github.com/philips-software/latrend/assets/137368713/aebfd524-a8cb-4e91-80a7-563c4924adb1">

**Comment by niekdt** [comment]
See the [clusterTrajectories](https://philips-software.github.io/latrend/reference/clusterTrajectories.html) function, which in case of KML, does give you the mean at each timepoint. The output of this function is used by `plot.lcModel` and `plotClusterTrajectories`.

```R
clusData = clusterTrajectories(kml_model_4)
aggregate(clusData, YourResponseVarHere ~ Cluster, min)
```

For other methods, the cluster trajectories are not necessarily the mean over the assigned trajectories. In that case, define a custom model using the [lcModelPartition](https://philips-software.github.io/latrend/reference/lcModelPartition.html) function and then extract its cluster trajectories.

**Comment by hichew22** [comment]
Thank you! If I assigned the trajectories based on a custom group (for example, rather than 4 clusters in the KML model the trajectories were assigned based on pre-defined groups A, B, C, D), would the cluster trajectories be the mean over the assigned pre-defined groups?

**Comment by niekdt** [comment]
Correct. The default function to compute the cluster center for `lcModelPartition` is `meanNA()`; see the  `center` argument of the `lcModelPartition` function.

**Comment by hichew22** [comment]
Thank you very much!
