### ISSUE TITLE
Modifying plot colors

### ISSUE THREAD

**Issue by hichew22** [philips-software/latrend#155]
Hello,

Previously in plotting the individual and cluster trajectories, the individual trajectories were black, and the cluster trajectories were colored (red, blue, green, etc.) like so:
<img width="658" alt="image" src="https://github.com/philips-software/latrend/assets/137368713/b2e28e4f-2153-4525-b683-12269cb53b27">

However, now this is reversed where the individual trajectories are colored and the cluster trajectories are black (my plot below). How can I revert to the original version?
<img width="680" alt="image" src="https://github.com/philips-software/latrend/assets/137368713/acb2b45d-a17f-469b-ba96-c592b4b35fa5">

Thank you!

**Comment by niekdt** [comment]
I'm thinking to rework the plotting such that `plotClusterTrajectories()` is consistent in drawing colored trends, as it does different things right now depending on the options, which is confusing. `plot()` will become the adaptive function then.


In the meantime, you can use:
```R
data(latrendData)
method <- lcMethodLMKM(Y ~ Time, id = "Id", time = "Time")
model <- latrend(method, latrendData, nClusters = 3)

ggplot() + 
    geom_line( data = trajectories(model), aes( x = Time, y = Y, group = Id)) + 
    facet_wrap(~ Cluster) + 
    geom_line(data = clusterTrajectories(model), aes(x = Time, y = Y, color = Cluster))
```

![image](https://github.com/philips-software/latrend/assets/8193083/04df6a80-f7f3-469c-9b31-62ead082fcc7)

**Comment by niekdt** [comment]
I'm not familiar with ggplot's labeller. An alternative way is to create a new cluster column with the labels that you want (that's how I implemented it in `plotClusterTrajectories`)

You can use `clusLabels = make.clusterPropLabels(clusterNames(kml_model_4), clusterSizes(kml_model_4))` to generate the labels.
Then create a new column, remapping the clusters to the labels:
```R
df_kml_model_cluster_traj$ClusterLabel = factor(df_kml_model_cluster_traj$Cluster, levels = clusterNames(kml_model_4), labels = clusLabels)
```

Then use ClusterLabel as the grouping/facet/color variable in ggplot

**Comment by niekdt** [comment]
Yes you'll need to add identical labels to that data frame too
