### ISSUE TITLE
lcMethodLMKM: detailed procedure

### ISSUE THREAD

**Issue by zh-zhang1984** [philips-software/latrend#91]
Dear authors,
I am confusing on the methodology behind lcMethodLMKM function, are there any hints /reference for this procedure? I searched in internet but find nothing to be relevant.

**Comment by niekdt** [comment]
Thanks for your question. The documentation of the `lcMethodLMKM` function is indeed lacking, I will extend it.

In the meantime, I'll try to answer your question:
`lcMethodLMKM` is an implementation of a type of individual time series (ITS) approach, also known as a feature-based approach, where each trajectory is represented by the coefficients of an individually fitted linear regression model. The trajectories are then clustered based on the coefficients using k-means. LMKM is not an established name or specific method, so I don't have any references for it.

I've described the feature-based approach in more detail in a general tutorial on longitudinal clustering: https://arxiv.org/abs/2111.05469, see Section 4.3

### Similar methods:
#### Anchored k-medoids
A linear regression representation approach is also used in [Anchored k-medoids](https://cran.r-project.org/package=akmedoids) (see [lcMethodAkmedoids](https://philips-software.github.io/latrend/reference/lcMethodAkmedoids.html)), but as far as I'm aware the package does not enable you to specify the linear regression model to use.

#### GCKM
The LMKM method is similar to GCKM (as implemented in `lcMethodGCKM`), except that for GCKM the coefficients are determined using a linear mixed model (a growth curve model), which should be more robust.

GCKM has been described and compared in:
* Twisk, J., and T. Hoekstra. 2012. Classifying developmental trajectories over time should be done with great caution: A comparison between methods. Journal of Clinical Epidemiology 65 (10):1078–87. doi:10.1016/j.jclinepi.2012.04.010. https://pubmed.ncbi.nlm.nih.gov/22818946/
*  N. G. P. Den Teuling, S. C. Pauws & E. R. van den Heuvel (2021) A comparison of methods for clustering longitudinal data with slowly changing trends, Communications in Statistics - Simulation and Computation, DOI: 10.1080/03610918.2020.1861464 https://www.tandfonline.com/doi/full/10.1080/03610918.2020.1861464

**Comment by zh-zhang1984** [comment]
thank you for the excellent explanation and references. I will read into it.
