### ISSUE TITLE
NA/NaN/Inf in foreign function call (arg 2)

### ISSUE THREAD

**Issue by yuwenhuang717** [philips-software/latrend#94]
Hi, thank you for developing this package. I wanted to do the clustering for my data, but continuously get the error "NA/NaN/Inf in foreign function call (arg 2)". I already checked there are no nan or inf in my data. Could you help me solve this issue? Many thanks!

**Comment by niekdt** [comment]
Hi, nice to hear you're using my package. Which type of `lcMethod` are you using?

Coincidentally there was another issue 2 days ago with the same error message, but perhaps with a different cause. 

Please check if your dataset contains any trajectories with only 1 observation, as that has been shown to cause this error.
If you're unsure how to check this, you can install latrend v1.2.2 (released today) as it includes a warning when this data issue is present.

You can install latrend v1.2.2 by running:
```r
remotes::install_github('philips-software/latrend', ref = remotes::github_release())
```

**Comment by yuwenhuang717** [comment]
Hi, many thanks for your reply. I just tried, and there is no warning message shown. 

I am using lcMethodMclustLLPA function for my longitudinal data.

Thank you very much again for your help!

**Comment by niekdt** [comment]
Are you using a public dataset? Is there any way in which I can reproduce the issue?

As `lcMethodMclustLLPA` is using the [mclust](https://cran.r-project.org/package=mclust), you may find clues/answers if you search for errors online related to `mclust()`.'

I found this:
https://stackoverflow.com/questions/46485202/mclust-nas-in-foreign-function-call-arg-13
Do you have observations with discrete or identical values?

**Comment by yuwenhuang717** [comment]
> 
[example.csv](https://github.com/philips-software/latrend/files/7929646/example.csv)
[](url)

The attached is an example data I was trying to cluster. 
Many thanks again for your time and help!

**Comment by niekdt** [comment]
Great, that helps a lot. There are a lot of repeated values in your data. It's likely that one of the clusters identified by `mclust()` consists solely of trajectories with `X.Requested.Heating.Power. = 1`, resulting in a variance of zero, and thus infinite density.

I would recommend to use KmL instead (see `lcMethodKML`) as it is very similar to LLPA, but is not affected by zero within-cluster variance.

Due to the extreme values in your data you may want to consider transforming the data, e.g., using a log-transform.

**Comment by yuwenhuang717** [comment]
Many thanks for your suggestion and reply.

I just tried lcMethodKML, but the other error showed:

![image](https://user-images.githubusercontent.com/75684208/151020408-c4a8aa63-3d2b-4f3f-b270-22c124cd7033.png)

Could you help me again with this issue?

Thank you very much!

**Comment by niekdt** [comment]
KML requires all trajectories to have the same number of observations, at the same time points. 
I think LLPA has the same requirement actually, so I'm not sure why you didn't get the same error for LLPA.

After taking a closer look at the data you shared, there's over a 1000 observations per trajectory. You need to ensure all trajectories are of equal length (e.g., selecting only the observations for _Time = 0, 1, ..., 1000_) or use a different method.

Given the length of the trajectories in your data I would suggest a feature-based approach. You could try `lcMethodDtwclust` for a time series clustering approach, or methods based on linear regression such as `lcMethodAkmedoids`, `lcMethodLMKM`.

**Comment by yuwenhuang717** [comment]
Okay, thank you very much for your help! I really appreciate it!

**Comment by niekdt** [comment]
You're welcome!
